name: build-site
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - uses: jetli/wasm-pack-action@v0.3.0

      - name: Build interop module
        working-directory: interop
        run: npm install

      - name: Build rust module
        working-directory: rust
        run: |
          npm install
          wasm-pack build

      - name: Build js module
        working-directory: js
        run: npm build

      - uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: gh-pages
          FOLDER: js/public
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}