name: build-site
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - uses: jetli/wasm-pack-action@v0.3.0

      - run: cd ./interop
      - run: npm install
      - run: cd ../rust
      - run: npm install
      - run: wasm-pack build
      - run: cd ../js
      - run: npm build

      - uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: gh-pages
          FOLDER: public
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}